Feat/base models
Team88888/Funtech_backend pull request #3
Opened 2024-04-02 17:48 UTC by find-y

2024-04-02 19:22 UTC, alexpro2022 requested changes
Добавить модели в админку

2024-04-02 19:22 UTC, alexpro2022 commented on funtech_proj/events/models.py
> +    head_image = models.ImageField(
- добавить поле upload_to
- добавить Pillow в dev.requirements.txt

2024-04-02 19:22 UTC, alexpro2022 commented on funtech_proj/events/models.py
> +        verbose_name='Организатор',
добавить related_name="organized_events" или что-то подобное, чтобы в ЛК была возможность показа организованных юзером ивентов

2024-04-02 19:22 UTC, alexpro2022 commented on funtech_proj/events/models.py
> +        User,
добавить related_name="participated_events" или что-то подобное, чтобы в ЛК была возможность показа посещенных/предстоящих юзером ивентов

2024-04-02 19:22 UTC, alexpro2022 commented on funtech_proj/events/models.py
> +        through='UsesEvent',
исправить на "ParticipantEvent"

2024-04-02 19:22 UTC, alexpro2022 commented on funtech_proj/funtech_proj/settings.py
>      "django.contrib.contenttypes",
Зарегистрировать приложения

2024-04-03 21:17 UTC, find-y commented on funtech_proj/funtech_proj/settings.py
>      "django.contrib.contenttypes",
что-то еще нужно сделать для этого?

2024-04-04 10:42 UTC, merged